<?php 
// функции общего назначения ..
module_load_include('inc','mkmod','mkmod.funcs');
// http://dev.masterkrowli.ru/profnastil-dlya-zabora
// http://dev.masterkrowli.ru/tehnoelast
// http://api.drupalhelp.net/api/commerce/constants/7
module_load_include('inc','mkmod','mkmod.forms');
module_load_include('inc','mkmod','mkmod.blocks');
module_load_include('inc','mkmod','mkmod.tokens');
//module_load_include('inc','mkmod','mkmod.callbacks');
module_load_include('inc','mkmod','mkmod.formatters');
module_load_include('inc','mkmod','mkmod.widgets');
module_load_include('inc','mkmod','mkmod.fields');
module_load_include('inc','mkmod','mkmod.themes');

module_load_include('inc','mkmod','mkmod.preprocess');
module_load_include('inc','mkmod','mkmod.alter');
/**
 * альтер для сущностей ..
 */
function mkmod_entity_info_alter(&$ei)
{
	// добавляем . стиль отображения для нод во всплывашке ..
	$ei['node']['view modes']['inpopup']=[
		'label'=>'Контент во всплывашке',
		'custom settings'=>1,
	];
	// добавили поле vis в сущность 
	$ei['taxonomy_term']['schema_fields_sql']['base table'][]='vis';
	$ei['taxonomy_term']['base table field types']['vis']='int';
	//dsm($ei,'$ei');
}



function mkmod_library()
{
	$p=drupal_get_path('module','mkmod');
	return [
		'myajaxcommands'=>[
			'title'=>'Мои команды',
			'webite'=>'',
			'version'=>'',
			'js'=>[
				['data'=>$p.'/myajaxcommands.js','type'=>'file'],
			],
			'dependencies'=>[
				['system','drupal.ajax'],
				['mklibs','fancybox'],
			],
		],
		'jqautocompleter'=>array(
			'title'=>'jquery-autocompleter',
			'website'=>'https://github.com/ArtemFitiskin/jquery-autocompleter',
			'version'=>'',
			'js'=>array(
				array('data'=>$p.'/jqac/jquery.autocompleter.js','type'=>'file'),
				array('data'=>$p.'/jqac/jqac-init.js','type'=>'file'),
			),
			'css'=>array(
				array('data'=>$p.'/jqac/jquery.autocompleter.css','type'=>'file'),
			),
		),
	];
}
// ===============================================
function mkmod_init()
{
	global $pp_size;
	$pp_size=10;
	if (!empty($_COOKIE['pp-size']) && intval($_COOKIE['pp-size']))
		$pp_size=$_COOKIE['pp-size'];
	//dsm($_COOKIE);
	//pp-size
}




// =======================================================
function mkmod_getrekvlist(){
	return array(
		'short-name'=>'Краткое наименование организации',
		'ur-addres'=>'Юридический адрес',
		'fakt-addres'=>'Фактический адрес',
		'inn'=>'ИНН',
		'kpp'=>'КПП',
		'ogrn'=>'ОГРН',
		'full-bank-name'=>'Полное наименование банка',
		'rs'=>'Номер расчетный счет',
		'kor-s'=>'Номер корреспондентского счета',
		'bik'=>'БИК',
		'timejob1'=>'Время работы 1',
		'timejob2'=>'Время работы 2'
	);
}
// =================================================
function mkmod_permission()
{
	return array(
		'admine pages'=>['title'=>'Админко',],
		'skladlist editor'=>array(
			'title'=>'Управнение складами',
		),
	);
}
// =======================================================
function mkmod_menu()
{
	return array(
		// отображаем страницу каталога 
		'catalog'=>[
			'title'=>'Каталог товаров',
			'page callback'=>'catalog_list_cb',
			'access arguments'=>['access content'],
			'file'=>'mkmod.callbacks.inc',
		],
		// отдать субэлемент каталога 
		'catalog-get-sub-ajax'=>[
			'type'=>MENU_CALLBACK,
			'page callback'=>'catalog_subitem_list_jscb',
			'access arguments'=>['access content'],
			'delivery callback'=>'ajax_deliver',
			'file'=>'mkmod.callbacks.inc',
		],
		'bestsellers'=>[
			'title'=>'Топ продаж',
			'access arguments'=>['access content'],
			'page callback'=>'bestsellers_cb',
			'file'=>'mkmod.callbacks.inc',
		],
		'discounts'=>[
			'title'=>'Акции',
			'access arguments'=>['access content'],
			'page callback'=>'akciilist_page_cb',
			'file'=>'mkmod.callbacks.inc',
		],
		'discounts/view'=>[
			'title'=>'Просмотр',
			'weight'=>5,
			'type'=>MENU_DEFAULT_LOCAL_TASK,
		],
		'discounts/config'=>[
			'title'=>'Настройки',
			'weight'=>10,
			'type'=>MENU_LOCAL_TASK,
			'access arguments'=>['admine pages'],
			'page callback'=>'drupal_get_form',
			'page arguments'=>['discounts_config_form'],
			'file'=>'mkmod.admin.inc',
		],

		// всплывашка контентом ноды .
		'get-node-in-popup/%node'=>[
			'type'=>MENU_CALLBACK,
			'page callback'=>'_get_node_in_popup_cb',
			'page arguments'=>[1],
			'access callback'=>'node_access',
			'access arguments'=>['view',1],
			'delivery callback'=>'ajax_deliver',
			'file'=>'mkmod.callbacks.inc',
		],
		// всплывашка формой . 
		'get-form-in-popup'=>[
			'type'=>MENU_CALLBACK,
			'page callback'=>'_get_form_in_popup_cb',
			'page arguments'=>[1],
			'access arguments'=>['access content'],
			'delivery callback'=>'ajax_deliver',
			'file'=>'mkmod.callbacks.inc',
		],
		// всплывашка шаблоном (шаблоны правятся через админку ..)
		'get-tpl-in-popup'=>[
			'type'=>MENU_CALLBACK,
			'access arguments'=>['access content'],
			'page callback'=>'get_tpl_in_popup_cb',
			'delivery callback'=>'ajax_deliver',
			'file'=>'mkmod.callbacks.inc',
		],
		// список шаблонов которыми можно всплыть  через  get-tpl-in-popup 
		'admin/config/administration/mkmod/tpls-editor'=>[
			'type'=>MENU_LOCAL_TASK,
			'title'=>'Редактор шаблонов ',
			'access arguments'=>['admine pages'],
			'page callback'=>'tpls_view_cb',
			//'page callback'=>'drupal_get_form',
			//'page arguments'=>array('kmodproductstabs_form'),
			'file'=>'mkmod.admin.inc',
		],
		'admin/config/administration/mkmod/tpls-editor/%'=>[
			'title'=>'Редактирование шаблона ',
			'access arguments'=>['admine pages'],
			//'page callback'=>'tpls_view_cb',
			'page callback'=>'drupal_get_form',
			'page arguments'=>['tpleditor_form',5],
			'file'=>'mkmod.admin.inc',
		],

		'news'=>[
			'title'=>'Новости',
			'access arguments'=>['access content'],
			'page callback'=>'content_view_cb',
			'page arguments'=>['new'],
			'file'=>'mkmod.callbacks.inc',
		],
		'articles'=>[
			'title'=>'Новости',
			'access arguments'=>['access content'],
			'page callback'=>'content_view_cb',
			'page arguments'=>['article'],
			'file'=>'mkmod.callbacks.inc',
		],
		// получить списоки нод ..
		'get-nodes-list'=>[
			'type'=>MENU_CALLBACK,
			'access arguments'=>['access content'],
			'page callback'=>'get_nodes_list_jscb',
			'file'=>'mkmod.callbacks.inc',
			'delivery callback'=>'ajax_deliver',
		],
		// погрузка контента на страницу списка товаров ( страница раздела таксономия )
		'get-next-content-elements'=>[
			'access arguments'=>['access content'],
			'page callback'=>'get_next_content_elements_jscb',
			'delivery callback'=>'ajax_deliver',
			'file'=>'mkmod.callbacks.inc',
		],

//--------------
		'get-comments-list'=>array(
			'type'=>MENU_CALLBACK,
			'access arguments'=>array('access comments'),
			'page callback'=>'_get_comments_list_cb',
			'delivery callback'=>'ajax_deliver',
		),

		'admin/config/administration/mkmod'=>array(
			'title'=>'Админко',
			'access arguments'=>array('admine pages'),
			'page callback'=>'drupal_get_form',
			'page arguments'=>array('mkmodadmin_form'),
			'file'=>'mkmod.admin.inc',
		),
		'admin/config/administration/mkmod/common'=>array(
			'type'=>MENU_DEFAULT_LOCAL_TASK,
			'title'=>'Быстрый заказ + отзывы',
		),
		'admin/config/administration/mkmod/otziv'=>array(
			'type'=>MENU_LOCAL_TASK,
			'title'=>'Рулим отзывами',
			'access arguments'=>array('admine pages'),
			'page callback'=>'drupal_get_form',
			'page arguments'=>array('mkmod_otzivs_form'),
			'file'=>'mkmod.admin.inc',
		),

		
			
		/// admine pages
		'admin/config/administration/sklads'=>array(
			'title'=>'Уравление складами',
			'access arguments'=>array('skladlist editor'),
			'page callback'=>'drupal_get_form',
			'page arguments'=>array('skladconfig_form'),
			'file'=>'mkmod.admin.inc',
		),
		

		'admin/product-finder'=>array(
			'title'=>'Поиск товаров',
			'access arguments'=>array('admine pages'),
			'page callback'=>'drupal_get_form',
			'page arguments'=>array('product_finder_form'),
			'options'=>array(
				'attributes'=>array(
					'class'=>array('rosoviy-text'),
				),
			),
		),
		'admin/config/system/site-information/infosite'=>array(
			'type'=>MENU_DEFAULT_LOCAL_TASK,
			'title'=>'Инфа о сайте ;)',
		),
		'admin/config/system/site-information/rekvisits'=>array(
			'type'=>MENU_LOCAL_TASK,
			'title'=>'Реквизиты',
			'page callback'=>'drupal_get_form',
			'page arguments'=>array('mkrekvisits_form'),
			'access arguments'=>array('admine pages'),
		),
	);
}

/**
 * запуск крона .. 
 * @return [type] [description]
 */
function mkmod_cron()
{
	$res=db_select('commerce_product','c');
	// есть старая цена 
	$res->leftjoin('field_data_field_old_price','o','o.entity_id=c.product_id and o.bundle=c.type');
	$res->isNotNull('o.field_old_price_amount');
	$res->condition('o.field_old_price_amount','','!=');
	// не в акции 
	$res->leftjoin('field_data_field_discount_from_date','d','d.entity_id=c.product_id and d.bundle=c.type');
	$res->where('not now() between d.field_discount_from_date_value and d.field_discount_from_date_value2');
	$res->fields('c',array('product_id'));
	$res=$res->execute()->fetchCol();
	if ($res){
		drupal_set_message(implode($res));
		
		$pp=commerce_product_load_multiple($res);
		foreach($pp as $p){
			$op=field_get_items('commerce_product',$p,'field_old_price');

			$p->commerce_price[LANGUAGE_NONE]=$op;
			$p->field_old_price=array();

			field_attach_presave('commerce_product',$p);
			field_attach_update('commerce_product',$p);
		}
	}
	drupal_set_message('asda');
}
// =====================================================================================
function mkmod_node_view($node, $view_mode, $langcode) 
{

	if ($view_mode=='full' && $node->type=='product_display'){
		// ранее просмотренные товары ..
		$viewed=empty($_COOKIE['prods-view'])?[]:explode(',',$_COOKIE['prods-view']);
		$nids=[];
		// зачистка от пустых значений .. 
		foreach($viewed as $v)
			if ($v && $v!=$node->nid)
				$nids[]=$v;

			$nc=15;
		if ($nids){// формируем вывод 
			$nn=array_chunk($nids, $nc);
			$oldvieved=&drupal_static('old-viewed-products-list');
			$oldvieved=$nn[0];
		}

		// добавляем новый элемент в начало ..
		array_unshift($nids, $node->nid);
		$nids=array_chunk($nids, $nc+5);
		$nids=end($nids);
		setcookie('prods-view',implode(',', $nids),REQUEST_TIME+3600*24*30);

	}
	return ;
	if ($view_mode=='full' && $node->type=='product_display'){

		// определяем какой таб показывать сейчас
		///dsm($node,'$node');
		//$fd=variable_get('product tabs config',array());
		//dsm($fd);
		
		if (!empty($fd['tabslist'])){
			$links=array();
			$rp=request_path();
			
			$url=path_load(array('source'=>'node/'.$node->nid));
			$url=empty($url['alias'])?'node/'.$node->nid:$url['alias'];
			//dsm($rp,$url);
			$fields=array(
				'info'=>'field_parameters_product',
				'characteristics'=>'field_harakteristic',
				'description'=>'field_text',
				'comments'=>'comments',
				'instructions-for-use'=>'field_instructions',
			);
			foreach($fd['tabslist'] as $x=>$y){
				if ($x!='comments'){
					$data=field_get_items('node',$node,$fields[$x]);
					if (empty($data))
						continue;
				}
				$l=array(
					'title'=>$y['title'].' '.($y['com']?sprintf('(%d)',$node->comment_count):''),
					'href'=>$url.($y['def']?'':'/'.$y['href']),
					'html'=>true,
				);
				if ($rp==$url.'/'.$y['href'] || $rp==$url && $y['def']){

					$l['attributes']['class'][]='active';
					$node->curtab=$x;
					if (!$y['def'])
						$node->titletaba=drupal_get_title().' '.drupal_strtolower($y['title']);
					$node->tabcontent=$fields[$x];
				}
				$links[]=$l;
			}
			$node->content['tabslinks']=array(
				'#attributes'=>array(
					'class'=>array('product-tabs'),
				),
				'#theme'=>'links',
				'#links'=>$links,	
			);		
		}




		//global $user;
		//dsm($user->roles[3]);
		// ранее просморенные товары
		$viewed=empty($_COOKIE['prods-view'])?[]:explode(',',$_COOKIE['prods-view']);
		$nids=[];
		// зачистка от пустых значений .. 
		foreach($viewed as $v)
			if ($v && $v!=$node->nid)
				$nids[]=$v;

			$nc=15;
		if ($nids){// формируем вывод 
			$nn=array_chunk($nids, $nc);
			$nn=node_view_multiple(node_load_multiple($nn[0]));
			foreach(element_children($nn['nodes']) as $k){
				$nn['nodes'][$k]['#prefix']='<div class="wrap">';
				$nn['nodes'][$k]['#suffix']='</div>';
			}
			//dsm($nn);
			$nn['#prefix']='<div class="field-items">';
			$nn['#suffix']='</div>';
			
			$node->content['prod-viewed']=array(
				'#type'=>'container',
				'#attributes'=>array('class'=>array('prod-viewed','field-type-node-reference')),
				'titl'=>array(
					'#prefix'=>'<div class="field-label">',
					'#suffix'=>'</div>',
					'#markup'=>'Ранее просмотренные товары',
				),
				'list'=>$nn,
			);
		}

		

		
	}
}

/// ====================================================
function _getcomentcontent($mkcc){
	global $pager_page_array;
	$n=node_load($mkcc['nid']);
	$pp=$mkcc['pp'];
	$cps=empty($mkcc['cps'])?array(0):$mkcc['cps'];// текущие страницы
	$cp=end($cps);

	$res=db_select('comment','c');
	$res->fields('c',array('cid'));
	$res->condition('c.nid',$n->nid);
	if (!user_access('administer comments'))
		$res->condition('c.status',1);
	$cids=$res->execute()->fetchCol();
	
	if (count($cids)>$pp && count($cps)*$pp<count($cids)){
		pager_default_initialize(count($cids),$pp);
		$pager_page_array[0]=$cp;
		$tags=array($cp==1?'noshow':'1','','','',);
		$tags[]=$cp+2==ceil(count($cids)/$pp)?'noshow':ceil(count($cids)/$pp);

		$pager=theme('pager',array('tags'=>$tags,'quantity'=>3));
		$pager=preg_replace('#<li.*?><a.*?>noshow</a></li>#i','',$pager);
		$out['pager']=array(
			'#type'=>'container',
			'#attributes'=>array('class'=>array('comment-list-pager','container-inline')),
			'nextbut'=>array(
				'#markup'=>'<div class="next-comment-butt">Показать ещё</div>',
			),
			'pager'=>array('#markup'=>$pager),
			'#weight'=>20,
		);
	}
	$cidsmas=array();
	foreach($cps as $x)
		$cidsmas=array_merge($cidsmas,array_slice($cids, $x*$pp,$pp));
	$out['comment-list']=comment_view_multiple(comment_load_multiple($cidsmas),$n);
	foreach(element_children($out['comment-list']) as $x)
  		unset($out['comment-list'][$x]['#prefix']);
  	

	return $out;

}

// =====================================================


// ============================================
function mkmod_form_alter(&$form,&$form_state,$form_id){
	if (empty($form_state['fselector']))
		$form_state['fselector']='form-hash-'.sha1(rand().REQUEST_TIME.rand());
	$form['#attributes']['class'][]=$form_state['fselector'];
	///добавоение к webform класса из админки 
	if (!empty($form['#node']) && $form['#node']->type=='webform' && !empty($form['#node']->nid)){
		$fd=variable_get('webforms mkmod adddons settings - '.$form['#node']->nid,array());
		if (!empty($fd)){
			$form['#attributes']['class'][]=$fd['csswrap'];
		}
	}
}


// ====================================================
// добавляем настроек для webform
function mkmod_form_webform_configure_form_alter(&$form,$form_state){
	$nid=$form['nid']['#value'];
	$fd=variable_get('webforms mkmod adddons settings - '.$nid,array());
	
	$form['advanced']['csswrap']=array(
		'#type'=>'textfield',
		'#title'=>'Обёрточный класс для формы',
		'#default_value'=>empty($fd['csswrap'])?'':$fd['csswrap'],
	);
	$form['#submit'][]='mkmodaddonswebformsettings_submit';
}
// ======================================================
function mkmodaddonswebformsettings_submit($form,$form_state){
	form_state_values_clean($form_state);
	$vals=$form_state['values'];
	///dsm($vals,'$vals');
	$fields=array();
	if (!empty($vals['csswrap']))
		$fields['csswrap']=$vals['csswrap'];

	variable_set('webforms mkmod adddons settings - '.$vals['nid'],$fields);
}


// =====================================================
// чистим таблицу кеша форм
function mkmod_flush_caches(){
	return array('cache_form');
}

// ===================================================
function mkmod_form_comment_node_product_display_form_alter(&$form,&$form_state){
	$form['actions']['submit']['#ajax']=array(
		'callback'=>'mkmodonsivajax_jscb',
	);
	unset($form_state['input']);
	//dsm($form_state['comment']);
	$fd=variable_get('mkmodadmin_form',array());
	$form_state['cc']=$fd['otsivs-count'];
}

// ==========================================================
function mkmodonsivajax_jscb($form,$form_state){
	$cmd=array();
	//$cmd[]=ajax_command_alert('das');
	// заменяем форму
	$form['mess']=array(
		'#theme'=>'status_messages',
		'#weigt'=>-3,
	);
	
	
	// обновить форму . 
	
	if (form_get_errors())  // если ошибоки еcnm надо обновить форму
		$cmd[]=ajax_command_replace('.form-selector-'.$form_state['fkey'],render($form));
	else{
		// чистить кеш меню
		cache_clear_all('admin_menu:','cache_menu',true);
		$cmd[]=ajax_command_replace('.form-selector-'.$form_state['fkey'],render($form['mess']));
		$cmd[]=array('command'=>'fancy-update');
	}
	
	// обновить списки коментов 
	/*$cc=array(
		'comment-wrap'=>array(
			'#type'=>'container',
			'#attributes'=>array(
				'class'=>array('comments-wrap'),
			),
		),
	);
	$cc['comment-wrap']=array_merge($cc['comment-wrap'],_getcomentcontent(array(
		'nid'=>$form_state['comment']->nid,
		'pp'=>$form_state['cc'],
	)));
	$cmd[]=ajax_command_replace('.comments-wrap',render($cc));*/
	// 
	return array('#type'=>'ajax','#commands'=>$cmd);
}

// ========================================================
function mkmod_form_menu_edit_item_alter(&$form,$form_state){
	array_unshift($form['#submit'],'mkmodmenuitemsavedata_sb');

	$form['get-node-in-popup']=array(
		'#type'=>'textfield',
		'#title'=>'Всплыть нодой',
		'#description'=>'Указать номер ноды',
		'#default_value'=>empty($form['options']['#value']['attributes']['data-show-node-in-popup'])?'':$form['options']['#value']['attributes']['data-show-node-in-popup'],
	);
}
// ============================================================
function mkmodmenuitemsavedata_sb($form,&$form_state){
	form_state_values_clean($form_state);
	$vals=&$form_state['values'];

	unset($vals['options']['attributes']['data-show-node-in-popup']);
	if (!empty($vals['get-node-in-popup']))
		$vals['options']['attributes']['data-show-node-in-popup']=$vals['get-node-in-popup'];
	unset($vals['get-node-in-popup']);

}

// ====================================================
function mkmod_form_block_admin_configure_alter(&$form,$form_state){
	/// block_add_block_form
	// запрос конфигурации 
	$fd=variable_get('mk-vis-conf-for-'.$form['module']['#value'].'-'.$form['delta']['#value'],array());
	
	$form['#submit'][]='mklistblocksalter_sb';
	$form['visibility']['mk']=array(
		'#type'=>'fieldset',
		'#title'=>'MK',
		'#tree'=>true,
		'#group'=>'visibility',
		'mkplaces'=>array(
			'#default_value'=>!empty($fd['mkplaces'])?$fd['mkplaces']:array(),
			'#type'=>'checkboxes',
			'#title'=>'отображать на:',
			'#options'=>array(
				'products'=>'Страницы витрин',
				'cats'=>'Страницы каталога',
				'front'=>'Главная',
			),
		),
	);
}
// =====================================
function mklistblocksalter_sb($form,$form_state){
	form_state_values_clean($form_state);
	$vals=$form_state['values'];
	variable_set('mk-vis-conf-for-'.$vals['module'].'-'.$vals['delta'],$vals['mk']);
	//dsm($form_state['values'],'save');

}




// ==================================================
// рулим роутингом чтобы добавить нужные нам табы не пользуя алиасы . 
function mkmod_url_inbound_alter(&$path,$pathorigin,$plang){
	// https://netspark.ru/useful/papers/nemnogo-dinamicheskogo-rautinga-v-drupal-7
	//$fd=variable_get('product tabs config',array());
	// нужно перебрать все алиасы и найти нужный 
	if(!empty($fd['tabslist']))
		foreach($fd['tabslist'] as $x=>$y)
			if (preg_match('#/'.$y['href'].'$#i',$pathorigin)){
				$alias=substr($pathorigin, 0,strlen($pathorigin)-strlen($y['href'])-1);
				$alias=drupal_lookup_path('source',$alias);
				if (!empty($alias))
					$path=$alias;
			}
}


// ===================================================
// пробуем чинить метатеги 
function mkmod_metatag_metatags_view_alter(&$output, $inst, $opt){
	if ($inst=='node:product_display' &&  $opt['view_mode']=='full'){
		//$fd=variable_get('product tabs config',array());
		if (!empty($fd['tabslist']))
			foreach($fd['tabslist'] as $k=>$taba){
				if ($taba['def'] || $k!=$opt['entity']->curtab)// пропустить дефолтную табу
					continue;
					
					$newval=$opt['entity']->title.' '.drupal_strtolower($taba['title']);
					if (!empty($output['title']['#attached']['metatag_set_preprocess_variable'][0][2]))
						$output['title']['#attached']['metatag_set_preprocess_variable'][0][2]=$newval;
					if (!empty($output['title']['#attached']['metatag_set_preprocess_variable'][1][2]['title']))
						$output['title']['#attached']['metatag_set_preprocess_variable'][1][2]['title']=$newval;
					if (!empty($output['description']['#attached']['drupal_add_html_head'][0][0]['#value']))
						$output['description']['#attached']['drupal_add_html_head'][0][0]['#value']=$newval;
			}
		
	}
}


/**
 * расширяем форму редактирования таксономии 
 */
function mkmod_form_taxonomy_form_term_alter(&$form,&$form_state)
{
	//$form['vis']=[
	//	'#type'=>'checkbox',
	//	'#title'=>'Видимый?',

	//];
	$vis=0;
	// делаем запрос на получение значения 
	if ($form['#entity']->tid){
		$res=db_select('taxonomy_term_data','t');
		$res->condition('t.tid',$form['#entity']->tid);
		$res->fields('t',['vis']);
		$res=$res->execute();
		$res=$res->fetch(PDO::FETCH_ASSOC);
		$vis=$res['vis'];
		$form['#submit'][]='vis_taxa_submit_cb';
		//dsm($form);
	}

	$form['visible']=[
		'#type'=>'checkbox',
		'#title'=>'Отображение раздела',
		'#default_value'=>$vis,
	];
	//dsm($form['#entity']->tid,'dsad');
	$form['relations']['parent']['#size']=15;
	//dsm($form);
}

/**
 * отправка формы . 
 */
function vis_taxa_submit_cb($form,$form_state)
{
	form_state_values_clean($form_state);
	$vals=$form_state['values'];
	if (empty($vals['tid']))
		return ;

	// обновление видимости .. 
	$res=db_update('taxonomy_term_data');
	$res->fields(['vis'=>$form_state['values']['visible']]);
	$res->condition('tid',$vals['tid']);
	$res->execute();
}


