<?php 
// http://dev.masterkrowli.ru/profnastil-dlya-zabora
// http://dev.masterkrowli.ru/tehnoelast
module_load_include('inc','mkmod','mkmod.forms');
module_load_include('inc','mkmod','mkmod.blocks');
module_load_include('inc','mkmod','mkmod.tokens');
module_load_include('inc','mkmod','mkmod.callbacks');
module_load_include('inc','mkmod','mkmod.formatters');
module_load_include('inc','mkmod','mkmod.widgets');
module_load_include('inc','mkmod','mkmod.fields');
module_load_include('inc','mkmod','mkmod.themes');
function mkmod_library(){
	$p=drupal_get_path('module','mkmod');
	return array(
		'fb'=>array(
			'title'=>'fancybox',
			'website'=>'http://fancyapps.com/fancybox/',
			'version'=>'2.1.7',
			'js'=>array(
				array('data'=>$p.'/fb/jquery.fancybox.pack.js','type'=>'file'),
			),
			'css'=>array(
				array('data'=>$p.'/fb/jquery.fancybox.css','type'=>'file'),
			),
		),
		'myajaxcommands'=>array(
			'title'=>'Мои команды',
			'webite'=>'',
			'version'=>'',
			'js'=>array(
				array('data'=>$p.'/myajaxcommands.js','type'=>'file'),
			),
			'dependencies'=>array(
				array('system','drupal.ajax'),
				array('mkmod','fb'),

			),
		),
		'jqautocompleter'=>array(
			'title'=>'jquery-autocompleter',
			'website'=>'https://github.com/ArtemFitiskin/jquery-autocompleter',
			'version'=>'',
			'js'=>array(
				array('data'=>$p.'/jqac/jquery.autocompleter.js','type'=>'file'),
				array('data'=>$p.'/jqac/jqac-init.js','type'=>'file'),
			),
			'css'=>array(
				array('data'=>$p.'/jqac/jquery.autocompleter.css','type'=>'file'),
			),
		),
	);
}
// ===============================================
function mkmod_init(){
	global $pp_size;
	$pp_size=10;
	if (!empty($_COOKIE['pp-size']) && intval($_COOKIE['pp-size']))
		$pp_size=$_COOKIE['pp-size'];
	//dsm($_COOKIE);
	//pp-size
}
//=======================================================
function mkmod_preprocess_page(&$p){
	nodetokens_replacer($p);
	//dsm(current_path());
	if (preg_match('#taxonomy/term/(\d+)#',current_path(),$tid) && !empty($p['page']['content']['system_main']['pager'])) {
		$pp=variable_get('default_nodes_main',10);
		$els=element_children($p['page']['content']['system_main']['nodes']);

		$tid=end($tid);
		
		if (1 ||strpos($_SERVER['HTTP_REFERER'], url(current_path()))!==false){
			
			//dsm($p);
			$p['page']['content']['system_main']['term_heading']['scroll-to']=[
				'#markup'=>'<span class="scroll-after-paginator"></span>',
			];
			//dsm($p['page']['content']['system_main']);
			//drupal_add_js()
			//dsm($_SERVER['HTTP_REFERER'],'REF');
		}
			//dsm([$_SERVER['REQUEST_URI'],],'serv');
		//dsm($p['page']['content']['system_main']['pager']);
		//dsm(pager_find_page());
		//$p['page']['content']['system_main']['pager']['#access']=false;
		$p['page']['content']['system_main']['nodes']['#type']='container';
		$p['page']['content']['system_main']['nodes']['load-more']=[
			'#access'=>$pp==count($els),
			'#type'=>'container',
			'#attributes'=>['class'=>['load-more-contents']],
			'button'=>[
				'#type'=>'button',
				'#value'=>'Загрузить ещё',
			],
			//'#markup'=>'<input type="button" value="Загрузить ещё" />',
			'#weight'=>1000,
		];
		$pagerparams=[
			'tid'=>$tid,
		];
		$args=drupal_get_query_parameters();
		//dsm($args);
		$p['page']['content']['system_main']['nodes']['#attributes']=[
			'class'=>['container-term-wrapp-autoload'],
			// товаров на страницу 
			'data-ppsize'=>variable_get('default_nodes_main',10),
			// текущаяя категория 
			'data-curtid'=>$tid,
			// текущая страница .. 
			'data-curpage'=>empty($args['page'])?0:$args['page'],
			
		];
		$p['page']['content']['system_main']['nodes']['#attached']['js'][]=drupal_get_path('module','mkmod').'/pager-uploader.js';
	}
	
	//
}
// =================================================
function mkmod_permission(){
	return array(
		'admine pages'=>array(
			'title'=>'Админко',
		),
		'skladlist editor'=>array(
			'title'=>'Управнение складами',
		),
	);
}
// =======================================================
function mkmod_getrekvlist(){
	return array(
		'short-name'=>'Краткое наименование организации',
		'ur-addres'=>'Юридический адрес',
		'fakt-addres'=>'Фактический адрес',
		'inn'=>'ИНН',
		'kpp'=>'КПП',
		'ogrn'=>'ОГРН',
		'full-bank-name'=>'Полное наименование банка',
		'rs'=>'Номер расчетный счет',
		'kor-s'=>'Номер корреспондентского счета',
		'bik'=>'БИК',
		'timejob1'=>'Время работы 1',
		'timejob2'=>'Время работы 2'
	);
}
// =======================================================
function mkmod_menu(){
	return array(
		'get-node-in-popup/%node'=>array(
			'type'=>MENU_CALLBACK,
			'page callback'=>'_get_node_in_popup_cb',
			'page arguments'=>array(1),
			'access callback'=>'node_access',
			'access arguments'=>array('view',1),
			'delivery callback'=>'ajax_deliver',
		),
		'get-form-in-popup'=>array(
			'type'=>MENU_CALLBACK,
			'page callback'=>'_get_form_in_popup_cb',
			'page arguments'=>array(1),
			'access arguments'=>array('access content'),
			'delivery callback'=>'ajax_deliver',
		),
		'get-tpl-in-popup'=>[
			'type'=>MENU_CALLBACK,
			'access arguments'=>['access content'],
			'page callback'=>'get_tpl_in_popup_cb',
			'delivery callback'=>'ajax_deliver',
		],
		'get-comments-list'=>array(
			'type'=>MENU_CALLBACK,
			'access arguments'=>array('access comments'),
			'page callback'=>'_get_comments_list_cb',
			'delivery callback'=>'ajax_deliver',
		),
		'get-next-content-elements'=>[
			'access arguments'=>['access content'],
			'page callback'=>'get_next_content_elements_jscb',
			'delivery callback'=>'ajax_deliver',
		],
		'admin/config/administration/mkmod'=>array(
			'title'=>'Админко',
			'access arguments'=>array('admine pages'),
			'page callback'=>'drupal_get_form',
			'page arguments'=>array('mkmodadmin_form'),
			'file'=>'mkmod.admin.inc',
		),
		'admin/config/administration/mkmod/common'=>array(
			'type'=>MENU_DEFAULT_LOCAL_TASK,
			'title'=>'Быстрый заказ + отзывы',
		),
		'admin/config/administration/mkmod/otziv'=>array(
			'type'=>MENU_LOCAL_TASK,
			'title'=>'Рулим отзывами',
			'access arguments'=>array('admine pages'),
			'page callback'=>'drupal_get_form',
			'page arguments'=>array('mkmod_otzivs_form'),
			'file'=>'mkmod.admin.inc',
		),

		'admin/config/administration/mkmod/tpls-editor'=>array(
			'type'=>MENU_LOCAL_TASK,
			'title'=>'Редактор шаблонов ',
			'access arguments'=>array('admine pages'),
			'page callback'=>'tpls_view_cb',
			//'page callback'=>'drupal_get_form',
			//'page arguments'=>array('kmodproductstabs_form'),
			'file'=>'mkmod.admin.inc',
		),
		'admin/config/administration/mkmod/tpls-editor/%'=>array(
			'title'=>'Редактирование шаблона ',
			'access arguments'=>array('admine pages'),
			//'page callback'=>'tpls_view_cb',
			'page callback'=>'drupal_get_form',
			'page arguments'=>array('tpleditor_form',5),
			'file'=>'mkmod.admin.inc',
		),
			
		/// admine pages
		'admin/config/administration/sklads'=>array(
			'title'=>'Уравление складами',
			'access arguments'=>array('skladlist editor'),
			'page callback'=>'drupal_get_form',
			'page arguments'=>array('skladconfig_form'),
			'file'=>'mkmod.admin.inc',
		),
		'bestsellers'=>array(
			'title'=>'Топ продаж',
			'access arguments'=>array('access content'),
			'page callback'=>'_bestsellers_cb',
		),
		'discounts'=>array(
			'title'=>'Акции',
			'access arguments'=>array('access content'),
			'page callback'=>'_akciilist_page_cb',
			'file'=>'mkmod.callbacks.inc',
		),
		'discounts/view'=>array(
			'title'=>'Просмотр',
			'weight'=>5,
			'type'=>MENU_DEFAULT_LOCAL_TASK,
		),
		'discounts/config'=>array(
			'title'=>'Настройки',
			'weight'=>10,
			'type'=>MENU_LOCAL_TASK,
			'access arguments'=>array('admine pages'),
			'page callback'=>'drupal_get_form',
			'page arguments'=>array('discounts_config_form'),
			'file'=>'mkmod.admin.inc',
		),
		'admin/product-finder'=>array(
			'title'=>'Поиск товаров',
			'access arguments'=>array('admine pages'),
			'page callback'=>'drupal_get_form',
			'page arguments'=>array('product_finder_form'),
			'options'=>array(
				'attributes'=>array(
					'class'=>array('rosoviy-text'),
				),
			),
		),
		'admin/config/system/site-information/infosite'=>array(
			'type'=>MENU_DEFAULT_LOCAL_TASK,
			'title'=>'Инфа о сайте ;)',
		),
		'admin/config/system/site-information/rekvisits'=>array(
			'type'=>MENU_LOCAL_TASK,
			'title'=>'Реквизиты',
			'page callback'=>'drupal_get_form',
			'page arguments'=>array('mkrekvisits_form'),
			'access arguments'=>array('admine pages'),
		),
	);
}

/// ====================================================
function _getcomentcontent($mkcc){
	global $pager_page_array;
	$n=node_load($mkcc['nid']);
	$pp=$mkcc['pp'];
	$cps=empty($mkcc['cps'])?array(0):$mkcc['cps'];// текущие страницы
	$cp=end($cps);

	$res=db_select('comment','c');
	$res->fields('c',array('cid'));
	$res->condition('c.nid',$n->nid);
	if (!user_access('administer comments'))
		$res->condition('c.status',1);
	$cids=$res->execute()->fetchCol();
	
	if (count($cids)>$pp && count($cps)*$pp<count($cids)){
		pager_default_initialize(count($cids),$pp);
		$pager_page_array[0]=$cp;
		$tags=array($cp==1?'noshow':'1','','','',);
		$tags[]=$cp+2==ceil(count($cids)/$pp)?'noshow':ceil(count($cids)/$pp);

		$pager=theme('pager',array('tags'=>$tags,'quantity'=>3));
		$pager=preg_replace('#<li.*?><a.*?>noshow</a></li>#i','',$pager);
		$out['pager']=array(
			'#type'=>'container',
			'#attributes'=>array('class'=>array('comment-list-pager','container-inline')),
			'nextbut'=>array(
				'#markup'=>'<div class="next-comment-butt">Показать ещё</div>',
			),
			'pager'=>array('#markup'=>$pager),
			'#weight'=>20,
		);
	}
	$cidsmas=array();
	foreach($cps as $x)
		$cidsmas=array_merge($cidsmas,array_slice($cids, $x*$pp,$pp));
	$out['comment-list']=comment_view_multiple(comment_load_multiple($cidsmas),$n);
	foreach(element_children($out['comment-list']) as $x)
  		unset($out['comment-list'][$x]['#prefix']);
  	

	return $out;

}
// =========================================================
// собрать акции 
function _getactionprodag(){
	// пробуем читать из кеша 
	$data=cache_get(__FUNCTION__);
	if (!empty($data->data) && $data->expire>REQUEST_TIME && 0)
		return $data->data;

	
	$res=db_select('node','n');
	$res->condition('n.status',1);
	$res->condition('n.type','product_display');
	// винтим товар //  и проверяем чтобы он был акционным
	$res->leftjoin('field_data_field_product_variations','pe','pe.entity_id=n.nid and pe.bundle=n.type');
	$res->leftjoin('commerce_product,','p','p.product_id=pe.field_product_variations_product_id and p.status=1');
	$res->leftjoin('field_data_field_discount_from_date','adate','adate.entity_id=p.product_id and adate.bundle=\'product\'');
	$res->where(' now() between adate.field_discount_from_date_value and (adate.field_discount_from_date_value2 +  interval 1 day)');
	// выкатываем интервал акции (с по)
	$res->addfield('adate','field_discount_from_date_value','afrom');
	$res->addfield('adate','field_discount_from_date_value2','ato');
	// проверяем чтобы была старая цена
	$res->leftjoin('field_data_field_old_price','oldp','oldp.entity_id=p.product_id and oldp.bundle=\'product\'');
	$res->condition('oldp.field_old_price_amount',0,'>');
	// собираем поля 
	$res->fields('n',array('nid','title'));

	$ff=array(
		array('field_title_top','value','titletop'),
		array('field_title_bot','value','titlebottom'),
		array('field_pic_product','fid',''),
	);
	foreach($ff as $i=>$v){
		$res->leftjoin('field_data_'.$v[0],"t$i","t$i.entity_id=n.nid and t$i.bundle=n.type and t$i.entity_type='node'");
		if ($v[2])
			$res->addField("t$i",$v[0].'_'.$v[1],$v[2]);
	}
	// добавляем ссыль на картинку товара 
	$res->leftjoin('file_managed','fm','fm.fid=t2.field_pic_product_fid');
	$res->fields('fm',array('uri'));
	// дергаем старую цену 
	$res->addField('oldp','field_old_price_amount','oldp');
	// дёргаем новую цену 
	$res->leftjoin('field_data_commerce_price','cp','cp.entity_id=p.product_id and cp.bundle=\'product\'');
	$res->addField('cp','commerce_price_amount','cp');
	// дёрнуть размерность 
	$res->leftjoin('field_data_field_unit_measure','m','m.entity_id=p.product_id and m.bundle=\'product\'');
	$res->leftjoin('taxonomy_term_data','td','td.tid=m.field_unit_measure_tid');
	$res->addField('td','name','measure');
	/// достать содержимое ... 
	$res->leftjoin('field_data_field_text','ft','ft.entity_id=n.nid and ft.bundle=n.type');
	$res->addField('ft','field_text_value','body');
	$res->range(0,100);
	$res=$res->execute()->fetchAllAssoc('nid',PDO::FETCH_ASSOC);
	//dsm($res,'$res');
	cache_set(__FUNCTION__,$res,'cache',REQUEST_TIME+3600*24);
	return $res;
}
// =========================================================
// достать нужное количество хитов прожаж
function _gethitprodag($count){
	$cid=__FUNCTION__.$count;
	$result=&drupal_static($cid);
	if ($result)
		return $result;
	$data=cache_get($cid);
	if (!empty($data->data) && $data->expire>=REQUEST_TIME){
		$result=$data->data;
		return $data->data;
	}
	
	$res=db_select('node','n');
	$res->condition('n.status',1);
	$res->condition('n.type','product_display');
	// исключаем метки 
	$res->leftjoin('field_data_field_marks_products','mark','mark.entity_id=n.nid and mark.bundle=n.type');
	$res->isNull('mark.field_marks_products_tid');
	// надо исключить акции 
	$res->leftjoin('field_data_field_product_variations','pe','pe.entity_id=n.nid and pe.bundle=n.type');
	$res->leftjoin('commerce_product,','p','p.product_id=pe.field_product_variations_product_id and p.status=1');
	$res->leftjoin('field_data_field_discount_from_date','adate','adate.entity_id=p.product_id and adate.bundle=\'product\'');
	///$res->leftjoin('field_data_field_old_price','oldp','oldp.entity_id=p.product_id and oldp.bundle=\'product\'');
	$res->where(' not now() between adate.field_discount_from_date_value and adate.field_discount_from_date_value2 ');
	// надо взять всетовары которые купили .. .
	$res->leftjoin('field_data_commerce_product','cp','cp.commerce_product_product_id=p.product_id');
	$res->leftjoin('commerce_line_item','li','li.line_item_id=cp.entity_id');
	// примотать таблицу ордеров ..
	$res->leftjoin('commerce_order','o','o.order_id=li.order_id');
	$st=module_invoke('commerce_order','statuses');
	
	foreach($st as $x=>$y)
		if ($y['cart'])
			unset($st[$x]);
	unset($st['canceled']);
	
	if ($st)
		$res->condition('o.status',array_keys($st));// куленый и оплаченный 

	$res->fields('n',array('nid'));
	
	$res->orderBy('o.created','desc');
	$res->range(0,$count);
	$res->groupBy('n.nid');
	$res=$res->execute()->fetchCol();
	$result=$res;
	cache_set($cid,$res,'cache',REQUEST_TIME+3600*24);
	return $res; 
}
// =====================================================
function mkmod_tokensshashreplacer($el){
	do{
		$a=md5($el);
		//dsm(array($el),$a);
		$el=token_replace($el);
	}while($a!=md5($el));
	//dsm(array($a,md5($el),$el));
	return $el;
}
// ===========================================
function nodetokens_replacer(&$el){
	foreach(array('#markup','#prefix','#suffix') as $k)
		if (is_array($el) && !empty($el[$k]))
			$el[$k]=mkmod_tokensshashreplacer($el[$k]);
	if (is_string($el))
		$el=mkmod_tokensshashreplacer($el);
	if (is_array($el))
		foreach(element_children($el) as $k)
			nodetokens_replacer($el[$k]);
}
// =======================================================
function mkmod_preprocess_node(&$n){

	if (!empty($n['elements']['#setpagetotrue']))
		$n['page']=true;
	if (preg_match('#^node/(\d+)$#',current_path(),$nod) && $nod[1]==$n['nid'])
		drupal_add_js(array('current-noda'=>$n['nid']),'setting');
	// замена токенов 
	if (!empty($n['content']))
		nodetokens_replacer($n['content']);
}
// ============================================
function mkmod_form_alter(&$form,&$form_state){
	if (empty($form_state['fselector']))
		$form_state['fselector']='form-hash-'.sha1(rand().REQUEST_TIME.rand());
	$form['#attributes']['class'][]=$form_state['fselector'];
	///добавоение к webform класса из админки 
	if (!empty($form['#node']) && $form['#node']->type=='webform' && !empty($form['#node']->nid)){
		$fd=variable_get('webforms mkmod adddons settings - '.$form['#node']->nid,array());
		if (!empty($fd)){
			$form['#attributes']['class'][]=$fd['csswrap'];
		}
	}

}
// ====================================================
// добавляем настроек для webform
function mkmod_form_webform_configure_form_alter(&$form,$form_state){
	$nid=$form['nid']['#value'];
	$fd=variable_get('webforms mkmod adddons settings - '.$nid,array());
	
	$form['advanced']['csswrap']=array(
		'#type'=>'textfield',
		'#title'=>'Обёрточный класс для формы',
		'#default_value'=>empty($fd['csswrap'])?'':$fd['csswrap'],
	);
	$form['#submit'][]='mkmodaddonswebformsettings_submit';
}
// ======================================================
function mkmodaddonswebformsettings_submit($form,$form_state){
	form_state_values_clean($form_state);
	$vals=$form_state['values'];
	///dsm($vals,'$vals');
	$fields=array();
	if (!empty($vals['csswrap']))
		$fields['csswrap']=$vals['csswrap'];

	variable_set('webforms mkmod adddons settings - '.$vals['nid'],$fields);
}
// =====================================================================================
function mkmod_node_view($node, $view_mode, $langcode) {
	if ($view_mode=='full' && $node->type=='product_display'){

		// определяем какой таб показывать сейчас
		///dsm($node,'$node');
		//$fd=variable_get('product tabs config',array());
		//dsm($fd);
		
		if (!empty($fd['tabslist'])){
			$links=array();
			$rp=request_path();
			
			$url=path_load(array('source'=>'node/'.$node->nid));
			$url=empty($url['alias'])?'node/'.$node->nid:$url['alias'];
			//dsm($rp,$url);
			$fields=array(
				'info'=>'field_parameters_product',
				'characteristics'=>'field_harakteristic',
				'description'=>'field_text',
				'comments'=>'comments',
				'instructions-for-use'=>'field_instructions',
			);
			foreach($fd['tabslist'] as $x=>$y){
				if ($x!='comments'){
					$data=field_get_items('node',$node,$fields[$x]);
					if (empty($data))
						continue;
				}
				$l=array(
					'title'=>$y['title'].' '.($y['com']?sprintf('(%d)',$node->comment_count):''),
					'href'=>$url.($y['def']?'':'/'.$y['href']),
					'html'=>true,
				);
				if ($rp==$url.'/'.$y['href'] || $rp==$url && $y['def']){

					$l['attributes']['class'][]='active';
					$node->curtab=$x;
					if (!$y['def'])
						$node->titletaba=drupal_get_title().' '.drupal_strtolower($y['title']);
					$node->tabcontent=$fields[$x];
				}
				$links[]=$l;
			}
			$node->content['tabslinks']=array(
				'#attributes'=>array(
					'class'=>array('product-tabs'),
				),
				'#theme'=>'links',
				'#links'=>$links,	
			);		
		}




		//global $user;
		//dsm($user->roles[3]);
		// ранее просморенные товары
		$viewed=empty($_COOKIE['prods-view'])?[]:explode(',',$_COOKIE['prods-view']);
		$nids=[];
		// зачистка от пустых значений .. 
		foreach($viewed as $v)
			if ($v && $v!=$node->nid)
				$nids[]=$v;

			$nc=15;
		if ($nids){// формируем вывод 
			$nn=array_chunk($nids, $nc);
			$nn=node_view_multiple(node_load_multiple($nn[0]));
			foreach(element_children($nn['nodes']) as $k){
				$nn['nodes'][$k]['#prefix']='<div class="wrap">';
				$nn['nodes'][$k]['#suffix']='</div>';
			}
			//dsm($nn);
			$nn['#prefix']='<div class="field-items">';
			$nn['#suffix']='</div>';
			
			$node->content['prod-viewed']=array(
				'#type'=>'container',
				'#attributes'=>array('class'=>array('prod-viewed','field-type-node-reference')),
				'titl'=>array(
					'#prefix'=>'<div class="field-label">',
					'#suffix'=>'</div>',
					'#markup'=>'Ранее просмотренные товары',
				),
				'list'=>$nn,
			);
		}

		// добавляем новый элемент в начало ..
		array_unshift($nids, $node->nid);
		$nids=array_chunk($nids, $nc+5);
		$nids=end($nids);
		setcookie('prods-view',implode(',', $nids),REQUEST_TIME+3600*24*30);

		
	}
}

// =====================================================
// чистим таблицу кеша форм
function mkmod_flush_caches(){
	return array('cache_form');
}
// ========================================================
// передаём в обёртку коментов число коментов на страницу
function mkmod_preprocess_comment_wrapper(&$vars){
	$fd=variable_get('mkmodadmin_form',array());
	if(!empty($fd['otsivs-count']))
		$vars['cc']=$fd['otsivs-count'];
}
// ===================================================
function mkmod_form_comment_node_product_display_form_alter(&$form,&$form_state){
	$form['actions']['submit']['#ajax']=array(
		'callback'=>'mkmodonsivajax_jscb',
	);
	unset($form_state['input']);
	//dsm($form_state['comment']);
	$fd=variable_get('mkmodadmin_form',array());
	$form_state['cc']=$fd['otsivs-count'];
}

// ==========================================================
function mkmodonsivajax_jscb($form,$form_state){
	$cmd=array();
	//$cmd[]=ajax_command_alert('das');
	// заменяем форму
	$form['mess']=array(
		'#theme'=>'status_messages',
		'#weigt'=>-3,
	);
	
	
	// обновить форму . 
	
	if (form_get_errors())  // если ошибоки еcnm надо обновить форму
		$cmd[]=ajax_command_replace('.form-selector-'.$form_state['fkey'],render($form));
	else{
		// чистить кеш меню
		cache_clear_all('admin_menu:','cache_menu',true);
		$cmd[]=ajax_command_replace('.form-selector-'.$form_state['fkey'],render($form['mess']));
		$cmd[]=array('command'=>'fancy-update');
	}
	
	// обновить списки коментов 
	/*$cc=array(
		'comment-wrap'=>array(
			'#type'=>'container',
			'#attributes'=>array(
				'class'=>array('comments-wrap'),
			),
		),
	);
	$cc['comment-wrap']=array_merge($cc['comment-wrap'],_getcomentcontent(array(
		'nid'=>$form_state['comment']->nid,
		'pp'=>$form_state['cc'],
	)));
	$cmd[]=ajax_command_replace('.comments-wrap',render($cc));*/
	// 
	return array('#type'=>'ajax','#commands'=>$cmd);
}
// ===================================================
function mkmod_preprocess_link(&$vars){

	// нужно подгрузить аякс команды .. 
	if (!empty($vars['options']['attributes']['data-show-node-in-popup']) && stripos(current_path(), 'admin')!==0){
		drupal_add_library('mkmod','myajaxcommands');
		$vars['options']['attributes']['class'][]='node-popup';
	}
		
}
// ========================================================
function mkmod_form_menu_edit_item_alter(&$form,$form_state){
	array_unshift($form['#submit'],'mkmodmenuitemsavedata_sb');

	$form['get-node-in-popup']=array(
		'#type'=>'textfield',
		'#title'=>'Всплыть нодой',
		'#description'=>'Указать номер ноды',
		'#default_value'=>empty($form['options']['#value']['attributes']['data-show-node-in-popup'])?'':$form['options']['#value']['attributes']['data-show-node-in-popup'],
	);
}
// ============================================================
function mkmodmenuitemsavedata_sb($form,&$form_state){
	form_state_values_clean($form_state);
	$vals=&$form_state['values'];

	unset($vals['options']['attributes']['data-show-node-in-popup']);
	if (!empty($vals['get-node-in-popup']))
		$vals['options']['attributes']['data-show-node-in-popup']=$vals['get-node-in-popup'];
	unset($vals['get-node-in-popup']);

}

// ====================================================
function mkmod_form_block_admin_configure_alter(&$form,$form_state){
	/// block_add_block_form
	// запрос конфигурации 
	$fd=variable_get('mk-vis-conf-for-'.$form['module']['#value'].'-'.$form['delta']['#value'],array());
	
	$form['#submit'][]='mklistblocksalter_sb';
	$form['visibility']['mk']=array(
		'#type'=>'fieldset',
		'#title'=>'MK',
		'#tree'=>true,
		'#group'=>'visibility',
		'mkplaces'=>array(
			'#default_value'=>!empty($fd['mkplaces'])?$fd['mkplaces']:array(),
			'#type'=>'checkboxes',
			'#title'=>'отображать на:',
			'#options'=>array(
				'products'=>'Страницы витрин',
				'cats'=>'Страницы каталога',
				'front'=>'Главная',
			),
		),
	);
}
// =====================================
function mklistblocksalter_sb($form,$form_state){
	form_state_values_clean($form_state);
	$vals=$form_state['values'];
	variable_set('mk-vis-conf-for-'.$vals['module'].'-'.$vals['delta'],$vals['mk']);
	//dsm($form_state['values'],'save');

}




// ==================================================
// рулим роутингом чтобы добавить нужные нам табы не пользуя алиасы . 
function mkmod_url_inbound_alter(&$path,$pathorigin,$plang){
	// https://netspark.ru/useful/papers/nemnogo-dinamicheskogo-rautinga-v-drupal-7
	//$fd=variable_get('product tabs config',array());
	// нужно перебрать все алиасы и найти нужный 
	if(!empty($fd['tabslist']))
		foreach($fd['tabslist'] as $x=>$y)
			if (preg_match('#/'.$y['href'].'$#i',$pathorigin)){
				$alias=substr($pathorigin, 0,strlen($pathorigin)-strlen($y['href'])-1);
				$alias=drupal_lookup_path('source',$alias);
				if (!empty($alias))
					$path=$alias;
			}
}


// ===================================================
// пробуем чинить метатеги 
function mkmod_metatag_metatags_view_alter(&$output, $inst, $opt){
	if ($inst=='node:product_display' &&  $opt['view_mode']=='full'){
		//$fd=variable_get('product tabs config',array());
		if (!empty($fd['tabslist']))
			foreach($fd['tabslist'] as $k=>$taba){
				if ($taba['def'] || $k!=$opt['entity']->curtab)// пропустить дефолтную табу
					continue;
					
					$newval=$opt['entity']->title.' '.drupal_strtolower($taba['title']);
					if (!empty($output['title']['#attached']['metatag_set_preprocess_variable'][0][2]))
						$output['title']['#attached']['metatag_set_preprocess_variable'][0][2]=$newval;
					if (!empty($output['title']['#attached']['metatag_set_preprocess_variable'][1][2]['title']))
						$output['title']['#attached']['metatag_set_preprocess_variable'][1][2]['title']=$newval;
					if (!empty($output['description']['#attached']['drupal_add_html_head'][0][0]['#value']))
						$output['description']['#attached']['drupal_add_html_head'][0][0]['#value']=$newval;
			}
		
	}
}

