<?php

module_load_include('inc','hitrolinks','hitrolinks.blocks');

function hitrolinks_permission()
{
	return [
		'access to hitrolinks'=>[
			'ttile'=>'Управление Хитрыми ссылками',
		],
	];
}

function hitrolinks_menu()
{
	$m=[];
	$tagsmenu=[
		'type'=>MENU_LOCAL_TASK,
		'title'=>'Теги',
		'page callback'=>'drupal_get_form',
		'page arguments'=>['hitro_groups_list_form','et'=>''],
		'access arguments'=>['access to hitrolinks'],
		'file'=>'hitrolinks.froms.inc',
	];
	$taglinksmenu=[
		'title'=>'Теги + ссылки',
			//'title callback'=>'hitro_title_links_cb',
			//'title arguments'=>[3],
		'page callback'=>'drupal_get_form',
		'page arguments'=>['hitro_links_list_form','et'=>''],
		'access arguments'=>['access to hitrolinks'],
		'file'=>'hitrolinks.froms.inc',
	];
	// товары 
	$tagsmenu['page arguments']['et']=$taglinksmenu['page arguments']['et']='node';
	$m['node/%/tags']=$tagsmenu;
	$m['node/%/tags/%']=$taglinksmenu;
	// разделы .. 
	$tagsmenu['page arguments']['et']=$taglinksmenu['page arguments']['et']='taxonomy';
	$m['taxonomy/term/%/tags']=$tagsmenu;
	$m['taxonomy/term/%/tags/%']=$taglinksmenu;

	// фильтры 
	$tagsmenu['title']='Фильтры';
	$taglinksmenu['title']='ссылки второй уровень';
	$tagsmenu['page arguments']['et']=$taglinksmenu['page arguments']['et']='filters';
	$m['taxonomy/term/%/filters']=$tagsmenu;
	$m['taxonomy/term/%/filters/%']=$taglinksmenu;

	return $m;


}

function hitro_title_links_cb($cat)
{
	$res=db_select('hl','t');
	$res->condition('t.id',$cat);
	$res->fields('t',['name']);
	$res=$res->execute()->fetch(PDO::FETCH_ASSOC);
	//dsm($res);
	return sprintf('Обзор тегов-ссылок для заголовка "%s"',$res['name']);
}

function hitrolinks_theme()
{
	return [
		'sortedtable'=>[
			'render element'=>'form',
			'file'=>'hitrolinks.themes.inc',
			//'template'=>'sortedtable',
		],
		'hitrolinkspopup'=>[
			'variables'=>['pid'=>0,'group'=>'group'],
			'file'=>'hitrolinks.themes.inc',
			'template'=>'hitrolinkspopup',
			'preprocess functions'=>[
				'popuplinks_prefunc',
			],
		],
		'katblockmenu'=>[
			'variables'=>[
				'menu'=>[],
				'limit'=>5,
			],
			//'render element'=>'menu',
			'template'=>'katblockmenu',
		],
	];
}

function hitrolinks_forms($form_id,$args)
{
	$ret=[];
	switch($form_id){
		case 'hitro_groups_list_form':
			$ret[$form_id]=[
				'callback'=>'hitro_list_form',
				'callback arguments'=>array_merge(['group'],$args),
			];
			break;

		case 'hitro_links_list_form':
			$ret[$form_id]=[
				'callback'=>'hitro_list_form',
				'callback arguments'=>array_merge(['link'],$args),
			];
			break;		
	}
	return $ret;
}


function hitrolinks_preprocess_page(&$vars)
{
	global $theme;
	if ($theme!=variable_get('theme_default'))
		return ;
	
	//dsm(current_path());
	$classes=[];

	$res=db_select('hl','t');
	$res->condition('t.active',1);

	$group=$pid=0;
	switch(arg(0)){
		case 'node':
			$group='ngroup';
			$pid=arg(1);
			break;
		case 'taxonomy':
			$group='tgroup';
			$pid=arg(2);
			break;
	}
	$res->condition('t.pid',$pid);
	$res->condition('t.type',$group);
	/// стыкуем ссылки .. 
	$res->leftjoin('hl','l','l.pid=t.id');
	$res->addExpression('sum(l.active)','co');
	$res=$res->execute()->fetch(PDO::FETCH_ASSOC);


	if (!empty($res['co']))
		$classes[]='active';
	//dsm($res);
	$place=&$vars['page']['content'];
	//kprint_r($group);
	if ($group=='ngroup')
		$place=&$vars['page']['content']['system_main'];


	$place['hl']=[ // 
		
		'#type'=>'container',
		'#weight'=>-100,
		'#attributes'=>['class'=>['hitrolinks-wrapper']],
		'#theme'=>'hitrolinkspopup',
		'#pid'=>$pid,
		'#group'=>$group,
	];
	uasort($place, 'element_sort');
	
	//dsm($vars);

}






function _createMenuFromList($res)
{
	$menu=[];
	for($i=0;$i<count($res); $i++){
		if (empty($menu[$res[$i]['gid']]))
			$menu[$res[$i]['gid']]=[
				'title'=>$res[$i]['gname'],
				'href'=>url($res[$i]['glink']),
				'weight'=>$res[$i]['gw']??0,
				'items'=>[],
			];
		if (isset($res[$i]['lid']) && $res[$i]['la'])
			$menu[$res[$i]['gid']]['items'][$res[$i]['lid']]=[
				'title'=>$res[$i]['lname'],
				'href'=>url($res[$i]['llink']),
				'weight'=>$res[$i]['lw']??0,
			];
	}
	foreach($menu as $x=>$y)
		uasort($menu[$x], 'drupal_sort_weight');
	uasort($menu, 'drupal_sort_weight');

	return $menu;
}




function hitrolinks_getotherfilters($from)
{
	// запрашиваем .. данные по ссылкам фильтров ... (формирование меню) 
		$res=db_select('hl','t1');
		$res->condition('t1.active',1);
		$res->condition('t2.active',1);
		$res->where('length(t1.link)=0');
		$res->orderBy('t1.weight','asc');
		$res->orderBy('t2.weight','asc');
		$res->leftJoin('hl','t2',"t2.pid=t1.id ");
		//$res->condition('t2.active',1);
		$res->addField('t1','id','gid');
		$res->addField('t1','weight','gw');
		$res->addField('t1','name','gname');
		$res->addField('t1','link','glink');
		$res->addField('t2','id','lid');
		$res->addField('t2','name','lname');
		$res->addField('t2','link','llink');
		$res->addField('t2','weight','lw');
		$res->addField('t2','active','la');

// http://dev.masterkrowli.ru/bitumnaya-gidroizolyaciya
		
		$res->condition('t1.type','fgroup');
		$res->condition('t1.pid',$from);
		
		$res=$res->execute()->fetchAll(PDO::FETCH_ASSOC);
		$menu=_createMenuFromList($res);
		///dsm($menu,$from);

	return $menu;
}

/**
 * вернуть ссылку по id из таблицы 
 * @param  int $id омер ссылки 
 * @return string     Ссылка если есть ...
 */
function hitrolinks_getLinkById($id)
{
	$res=db_select('hl','t');
	$res->condition('t.active',1);
	$res->condition('t.id',$id);
	$res->fields('t',['link']);
	$res=$res->execute()->fetchField();
	return $res;
	
}